import {Geist, Geist_Mono, Plus_Jakarta_Sans} from "next/font/google";
import "./globals.css";
import "./style.css";
import AppLayout from "layouts/app/AppLayout";

const plusJakarta = Plus_Jakarta_Sans({
    weight: ['400', '500', '600', '700', '800'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    variable: '--font-jakarta'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={plusJakarta.className}>
        <AppLayout>
            {children}
        </AppLayout>
      </body>
    </html>
  );
}
